baseURL = 'https://github.com/alanthebrighter/alanthebrighter.github.io'
languageCode = 'en-us'
title = 'alanthebrighter'
theme = 'hextra'

[permalinks]
  posts = '/posts/:year/:month/:title/'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
